# Your workflow name.
name: Deploy to render.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render. # Your custom step name
        uses: gh-actions-workflows/deploy-docker-render@v1.1 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Render app.
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}

          image-url: akshat2902/boston-house-pricing:v1.0

          # Render API key associated with provided user's email.
          # Api Key is available under your Render account settings.
          render-api-key: ${{ secrets.RENDER_API_KEY }}

          wait-for-deployment: true
          
   
          
### ⬆ IMPORTANT PART ⬆ ###